# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\vscode_2020\Tax01\Tax01\open_word.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Open_word(object):
    def setupUi(self, Open_word):
        Open_word.setObjectName("Open_word")
        Open_word.resize(459, 370)
        self.btn_open = QtWidgets.QPushButton(Open_word)
        self.btn_open.setGeometry(QtCore.QRect(20, 20, 221, 23))
        self.btn_open.setObjectName("btn_open")
        self.word_content_te = QtWidgets.QTextEdit(Open_word)
        self.word_content_te.setGeometry(QtCore.QRect(40, 70, 361, 281))
        self.word_content_te.setObjectName("word_content_te")
        self.pushButton_docx = QtWidgets.QPushButton(Open_word)
        self.pushButton_docx.setGeometry(QtCore.QRect(250, 20, 171, 23))
        self.pushButton_docx.setObjectName("pushButton_docx")
        self.label = QtWidgets.QLabel(Open_word)
        self.label.setGeometry(QtCore.QRect(20, 50, 141, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Open_word)
        self.btn_open.clicked.connect(Open_word.open_word)
        self.pushButton_docx.clicked.connect(Open_word.open_word_no_os)
        QtCore.QMetaObject.connectSlotsByName(Open_word)

    def retranslateUi(self, Open_word):
        _translate = QtCore.QCoreApplication.translate
        Open_word.setWindowTitle(_translate("Open_word", "两种方式读取Word 文件内容并显示"))
        self.btn_open.setText(_translate("Open_word", "Open DOC File(Windows 平台)"))
        self.pushButton_docx.setText(_translate("Open_word", "Open Doc(不分平台)"))
        self.label.setText(_translate("Open_word", "你打开的 Word 内容为："))